version: '3.8'
services:
  gymTrackServer:
    image: sellnat77/gym-track-server:v1
    container_name: gymTrackServer
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - 3000:3000
    build:
     context: ./gym-track-server
     dockerfile: Dockerfile
    volumes:
      - ./gym-track-server:/usr/src/app
    depends_on:
     - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local